### ISSUE TITLE
Release v0.7.4

### ISSUE THREAD

**Issue by yhara** [biwascheme/biwascheme#250]
- [x] Tests are green
- [x] fixed: `element-new` raises error (#235)
- [ ] fixed: `load` on Node (#245)
- [ ] fixed: Some library functions did not show proper error message (054989b)
- [x] fixed: `write` should stop for cyclic object (#238)
- [x] Update biwascheme_terminal to use `write` (#234)

**Comment by yhara** [comment]
Oops, src/deps/underscore-1.10.2-esm.js has security warning too..
